# The product as an author of a workflow transition (CPM-OPERATE-S11, CPM-AD-22).
#
# `actor` becomes nullable and `origin` arrives beside it, with a check
# constraint that exactly one of the two names the author -- the shape
# `collectors.InventoryChange` already uses for "a person, or the file an import
# read". The one product-authored move is closing the open items of a package
# the inventory no longer lists, recorded with `origin="system"`, a
# justification naming the absence, and no actor: the product holds no role and
# borrows nobody's account.
#
# **No data moves.** Every existing row names an actor and carries a blank
# origin, which is exactly the human half of the new constraint, so the
# constraint is added over them without a backfill.

# Generated by Django 5.2.15 on 2026-09-14 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_queue_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtransition',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='actor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_transitions', to=settings.AUTH_USER_MODEL, verbose_name='actor'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('origin', '')), models.Q(('actor__isnull', True), models.Q(('origin', ''), _negated=True)), _connector='OR'), name='workflow_transition_exactly_one_author'),
        ),
    ]
