"""A component booted from `config.settings.local` offers every package to both channel-reading collectors.

`CPM-OPERATE-S06` declares the published-conda surface in `local.py` so that a
local run observes conda-forge instead of selecting nothing for ever. Every
other case about that declaration reads the settings module or the pixi
manifest; none of them proves that a process which *boots* from `local` --
`manage.py`'s default, `config/asgi.py`'s and `config/celery_app.py`'s -- gets
through `CollectorsConfig.ready()`'s shape check with it and then offers the
inventory. That is what this module boots a child to show, on the shape
`test_collector_boot_refusal.py` established: a real `django.setup()` from a
settings module composed from `local`, a migrated scratch database, one seeded
package, and the two selections asked in the same process.

`tests/integration/conftest.py` marks everything under `tests/integration/` as an
integration test; the marker is not re-applied by hand.
"""

from __future__ import annotations

import json
import subprocess
import sys
from typing import TYPE_CHECKING
from typing import Final

from conda_sentinel.collectors.conda_package import COLLECTOR_NAME as CONDA_PACKAGE_NAME
from conda_sentinel.collectors.license import COLLECTOR_NAME as LICENSE_NAME
from config.locality import LOCAL
from config.locality import PROCESS_ENV_VAR
from config.locality import RUNTIME_ENV_VAR
from tests.conftest import subprocess_env
from tests.integration.startup.conftest import BOOT_PROBE_TIMEOUT_SECONDS

if TYPE_CHECKING:
    from collections.abc import Mapping
    from pathlib import Path

#: The package the child seeds, by canonical name. Any name does: both selections
#: offer the whole inventory or nothing, and one row is enough to tell the two apart.
A_SEEDED_PACKAGE: Final[str] = "cpm-local-surface-probe"

#: The settings module the child imports: `local`, on a scratch database.
_PROBE_SETTINGS_TEMPLATE: Final = '''\
"""A local component on a scratch database.

Generated by tests/integration/startup/test_local_monitored_surface.py.
"""

from config.settings.local import *  # noqa: F401, F403

DATABASES = {{
    "default": {{
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": {database!r},
    }},
}}
'''

#: The child. It boots, migrates, seeds one package, and reports what each
#: collector's selection offered alongside what the settings module declared.
#:
#: A string on purpose: nothing here executes in the test process, so the
#: `print`-free file handoff needs no ruff exemptions.
_PROBE_SOURCE: Final = '''
"""Boot from local settings, seed one package, and report both selections."""

import json
import sys
from pathlib import Path

import django

REPORT = Path(sys.argv[1])
NAME = sys.argv[2]

django.setup()

from django.conf import settings  # noqa: E402
from django.core.management import call_command  # noqa: E402
from django.utils import timezone  # noqa: E402

from conda_sentinel.collectors.conda_package import CondaPackageCollector  # noqa: E402
from conda_sentinel.collectors.license import LicenseCollector  # noqa: E402
from conda_sentinel.identity.models import Package  # noqa: E402

call_command("migrate", verbosity=0)
package = Package.objects.create(canonical_name=NAME, resolved_at=timezone.now())

REPORT.write_text(
    json.dumps(
        {
            "channels": list(settings.CPM_MONITORED_CHANNELS),
            "platforms": list(settings.CPM_MONITORED_PLATFORMS),
            "package": package.pk,
            "offered": {
                CondaPackageCollector.name: list(CondaPackageCollector.selectable_packages()),
                LicenseCollector.name: list(LicenseCollector.selectable_packages()),
            },
        }
    ),
    encoding="utf-8",
)
'''


def _booted_locally(tmp_path: Path) -> Mapping[str, object]:
    """Boot a child from `local` settings on a scratch database and return its report.

    Args:
        tmp_path: The directory the generated settings module, the report and the
            scratch database live in, and the only entry on the child's path.

    Returns:
        The child's report: the declared surface, the seeded package's key, and
        what each selection offered.

    """
    (tmp_path / "probe_settings.py").write_text(
        _PROBE_SETTINGS_TEMPLATE.format(database=str(tmp_path / "probe.sqlite3")),
        encoding="utf-8",
    )
    report_path = tmp_path / "surface.json"

    env = subprocess_env()
    # Local, because `local.py` is what is under test and stage 1's FR-12 escape
    # route refuses that module in a deployed run.
    env[RUNTIME_ENV_VAR] = LOCAL
    env.pop(PROCESS_ENV_VAR, None)
    env["DJANGO_SETTINGS_MODULE"] = "probe_settings"
    # The child's own working directory is the import root for its generated
    # module, so `PYTHONSAFEPATH` -- which is what keeps the interpreter from
    # prepending it -- has to go for this probe.
    env.pop("PYTHONSAFEPATH", None)

    completed = subprocess.run(  # noqa: S603
        [sys.executable, "-c", _PROBE_SOURCE, str(report_path), A_SEEDED_PACKAGE],
        cwd=tmp_path,
        env=env,
        capture_output=True,
        text=True,
        timeout=BOOT_PROBE_TIMEOUT_SECONDS,
        check=False,
    )

    assert completed.returncode == 0, (
        f"the local-surface probe exited {completed.returncode}\n"
        f"--- stdout ---\n{completed.stdout}\n--- stderr ---\n{completed.stderr}"
    )
    return json.loads(report_path.read_text(encoding="utf-8"))


def test_a_component_booted_from_local_settings_offers_every_package_to_both_collectors(tmp_path: Path) -> None:
    """`CPM-OPERATE-S06`, end to end in a real process.

    Three things, in the order they happen. The boot itself completes:
    `CollectorsConfig.ready()` ran both collectors' shape checks over the local
    declaration and refused neither. The process reads the declaration
    `local.py` makes. And with one package seeded, `conda_package` and `license`
    each offer exactly that package -- the "every package" half of the story's
    first criterion, which is what the empty declaration used to make impossible.
    """
    report = _booted_locally(tmp_path)

    assert report["channels"] == ["conda-forge"]
    assert report["platforms"] == ["noarch", "linux-64"]
    offered = report["offered"]
    assert isinstance(offered, dict)
    assert offered[CONDA_PACKAGE_NAME] == [report["package"]]
    assert offered[LICENSE_NAME] == [report["package"]]
