# Generated by Django 5.2.15 on 2026-09-12 20:17

# `identity_resolution_snapshots`, CPM-IDENTITY-S08's evidence of CPM-FR-1's
# resolver. Hand-edited once, on the terms 0002 through 0011 were: the
# autodetector named a later `identity` migration, and the only `identity`
# relation here is the PROTECT foreign key to `identity.Package`, which
# `0001_package_identity` creates. Depending on a later identity migration would
# order this one behind migrations it does not need.
#
# PROTECT, as EVIDENCE.02-AUDIT-001 requires of every relation on an evidence model
# -- Django's deletion collector bypasses every append-only refusal in
# core/models.py, so a CASCADE here would destroy a package's resolution history
# when the package went.
#
# Otherwise unedited: the model declares the whole of it -- the one read index
# core/freshness.py's query needs, and the one constraint.
#
# **This table is evidence of a resolution, not the resolution.** What the
# resolver established is written to `packages`, `package_mappings` and
# `feedstocks` through identity's `record_resolution` (CPM-AD-14), inside the
# same per-package transaction; this row is what each source said, which
# `project_urls` key was chosen, and what confidence the package held afterwards.
# The constraint is the biconditional every evidence table here carries: an `ok`
# row reached the recorder and records the confidence the package now holds, and
# a row that did not reach it records none of the recorder's facts. The JSON
# `feedstocks` column is outside it because JSON compares differently on the two
# backends this product runs against.
#
# There is no unique constraint of any kind (CPM-AD-2): resolving a package a
# second time is a new row and the first one stands. There is no data step: the
# table starts empty and the first sweep fills it.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0011_python_verification_results'),
        ('identity', '0001_package_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityResolutionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('source', models.CharField(blank=True, default='', max_length=512, verbose_name='source')),
                ('state', models.CharField(choices=[('error', 'Error'), ('unknown', 'Unknown'), ('not_found', 'Not Found'), ('not_applicable', 'Not Applicable'), ('ok', 'Ok')], max_length=32, verbose_name='state')),
                ('repository_url', models.URLField(blank=True, default='', max_length=512, verbose_name='repository URL')),
                ('repository_key', models.CharField(blank=True, default='', max_length=128, verbose_name='repository key')),
                ('pypi_asked', models.BooleanField(default=False, verbose_name='PyPI asked')),
                ('pypi_found', models.BooleanField(default=False, verbose_name='PyPI found')),
                ('pypi_source', models.CharField(blank=True, default='', max_length=512, verbose_name='PyPI source')),
                ('feedstocks', models.JSONField(blank=True, default=list, verbose_name='feedstocks')),
                ('confidence_recorded', models.CharField(blank=True, choices=[('verified', 'Verified'), ('inventory-derived', 'Inventory Derived'), ('unmapped', 'Unmapped')], default='', max_length=32, verbose_name='confidence recorded')),
                ('downgrade_refused', models.BooleanField(default=False, verbose_name='downgrade refused')),
                ('detail', models.TextField(blank=True, default='', verbose_name='detail')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_resolution_snapshots', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'identity resolution snapshot',
                'verbose_name_plural': 'identity resolution snapshots',
                'db_table': 'identity_resolution_snapshots',
                'indexes': [models.Index(fields=['package', '-observed_at'], name='id_resolution_pkg_observed')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('state', 'ok'), models.Q(('confidence_recorded', ''), _negated=True)), models.Q(models.Q(('state', 'ok'), _negated=True), ('confidence_recorded', ''), ('downgrade_refused', False), ('pypi_asked', False), ('pypi_found', False), ('pypi_source', ''), ('repository_key', ''), ('repository_url', '')), _connector='OR'), name='resolution_facts_present_exactly_when_recorded')],
            },
        ),
    ]
