# Generated by Django 5.2.15 on 2026-09-13 21:22

# `inventory` and `inventory_changes`: the governed inventory table and its audit
# trail (CPM-OPERATE-S03, CPM-FR-3 as amended). Otherwise unedited: the model
# declares the whole of it.
#
# `inventory` is the one table in this application that is NOT evidence. It is
# the reference data the ingestion collector reads through the database adapter
# (CPM-AD-29), mutated in place by `collectors/inventory.py`'s service and by
# nothing else; the two unique constraints -- one row per key, and one ACTIVE row
# per name, because the name becomes `Package.canonical_name` which is unique and
# create-only -- are permitted for exactly that reason, and retirement is the
# `retired_at` column rather than a delete.
#
# `inventory_changes` is evidence of every change -- prior and new value for every
# changeable field, the actor or the file, the reason -- written in the same
# transaction as the change (CPM-AD-14). PROTECT on both relations, as
# EVIDENCE.02-AUDIT-001 requires of every relation on an evidence model; the
# actor is nullable because an import runs unattended and then `origin` names
# the file, and a check constraint makes every row name exactly one of the two.
# No unique constraint of any kind (CPM-AD-2).
#
# Depends on this application's own leaf and on the user model, which is all it
# references. Not on any `core` migration: `core/0011_grant_inventory_change`
# depends on THIS one, so that the permission the model attaches exists before
# the grant looks for it, and a `core` rollback in the suite must not unapply
# this table (see the migration-rollback note in the project memory).
#
# The table starts empty. `manage.py import_watchlist` -- the `import-watchlist`
# admin process -- is what fills it from the reviewed file, and the demo seeder
# does the same for the development subset.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0012_identity_resolution_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_package_key', models.CharField(max_length=512, verbose_name='source package key')),
                ('package_name', models.CharField(max_length=128, verbose_name='package name')),
                ('internal_component_count', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='internal component count')),
                ('internal_lob_count', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='internal LOB count')),
                ('apps', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='apps')),
                ('platforms', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='platforms')),
                ('downloads', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='downloads')),
                ('versions', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='versions')),
                ('retired_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='retired at')),
                ('changed_at', models.DateTimeField(verbose_name='changed at')),
                ('reason', models.TextField(verbose_name='reason')),
            ],
            options={
                'verbose_name': 'inventory entry',
                'verbose_name_plural': 'inventory entries',
                'db_table': 'inventory',
                'ordering': ('source_package_key',),
                'indexes': [models.Index(fields=['retired_at'], name='inventory_retired_at')],
                'constraints': [models.UniqueConstraint(fields=('source_package_key',), name='inventory_key_is_one_row'), models.UniqueConstraint(condition=models.Q(('retired_at__isnull', True)), fields=('package_name',), name='inventory_active_name_is_one_row'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='inventory_change_states_its_reason')],
            },
        ),
        migrations.CreateModel(
            name='InventoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('origin', models.CharField(blank=True, default='', max_length=512, verbose_name='origin')),
                ('prior_package_name', models.CharField(blank=True, default='', max_length=128, verbose_name='prior package name')),
                ('new_package_name', models.CharField(max_length=128, verbose_name='new package name')),
                ('prior_internal_component_count', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='prior internal component count')),
                ('new_internal_component_count', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='new internal component count')),
                ('prior_internal_lob_count', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='prior internal LOB count')),
                ('new_internal_lob_count', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='new internal LOB count')),
                ('prior_apps', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='prior apps')),
                ('new_apps', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='new apps')),
                ('prior_platforms', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='prior platforms')),
                ('new_platforms', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='new platforms')),
                ('prior_downloads', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='prior downloads')),
                ('new_downloads', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='new downloads')),
                ('prior_versions', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='prior versions')),
                ('new_versions', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='new versions')),
                ('prior_retired', models.BooleanField(default=False, verbose_name='prior retired')),
                ('new_retired', models.BooleanField(default=False, verbose_name='new retired')),
                ('reason', models.TextField(verbose_name='reason')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('actor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_changes', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='collectors.inventoryentry', verbose_name='entry')),
            ],
            options={
                'verbose_name': 'inventory change',
                'verbose_name_plural': 'inventory changes',
                'db_table': 'inventory_changes',
                'ordering': ('-observed_at', '-id'),
                'permissions': [('change_inventory', 'Can change the inventory')],
                'indexes': [models.Index(fields=['entry', '-observed_at'], name='inv_change_entry_observed')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='inventory_change_row_states_its_reason'), models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('origin', '')), models.Q(('actor__isnull', True), models.Q(('origin', ''), _negated=True)), _connector='OR'), name='inventory_change_names_a_person_or_a_file')],
            },
        ),
    ]
