# Generated by Django 5.2.15 on 2026-09-14 02:16

# One bare `observed_at` index on each of the eleven evidence tables the nightly
# purge scans by cut-off (CPM-OPERATE-S07). Every read index on these tables
# leads with the package and cannot serve a scan that names none; without these
# a purge over a table that grows by the inventory every day is a sequential
# scan every night. Named per the `*_TIME_INDEX` constants in
# collectors/models.py. Otherwise unedited: the models declare the whole of it.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0013_inventory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='condapackagesnapshot',
            index=models.Index(fields=['observed_at'], name='conda_pkg_observed'),
        ),
        migrations.AddIndex(
            model_name='feedstocksnapshot',
            index=models.Index(fields=['observed_at'], name='feedstock_observed'),
        ),
        migrations.AddIndex(
            model_name='identityresolutionsnapshot',
            index=models.Index(fields=['observed_at'], name='id_resolution_observed'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['observed_at'], name='inv_snapshot_observed'),
        ),
        migrations.AddIndex(
            model_name='kevfinding',
            index=models.Index(fields=['observed_at'], name='kev_finding_observed'),
        ),
        migrations.AddIndex(
            model_name='licensefinding',
            index=models.Index(fields=['observed_at'], name='license_finding_observed'),
        ),
        migrations.AddIndex(
            model_name='pypireleasesnapshot',
            index=models.Index(fields=['observed_at'], name='pypi_release_observed'),
        ),
        migrations.AddIndex(
            model_name='pythonreadinessassessment',
            index=models.Index(fields=['observed_at'], name='py_readiness_observed'),
        ),
        migrations.AddIndex(
            model_name='pythonverificationresult',
            index=models.Index(fields=['observed_at'], name='py_verify_observed'),
        ),
        migrations.AddIndex(
            model_name='sourcereleasesnapshot',
            index=models.Index(fields=['observed_at'], name='src_release_observed'),
        ),
        migrations.AddIndex(
            model_name='vulnerabilityfinding',
            index=models.Index(fields=['observed_at'], name='vuln_finding_observed'),
        ),
    ]
