# Generated by Django 5.2.15 on 2026-09-14 03:59

# `package_recollections`: the audit row a "Collect now" press writes before the
# per-package collection tasks are published (CPM-OPERATE-S08, CPM-UJ-1).
# Otherwise unedited: the model declares the whole of it.
#
# Evidence of a human act, on `inventory_changes`' terms: append-only, one row per
# press, PROTECT on both relations as EVIDENCE.02-AUDIT-001 requires, no unique
# constraint (CPM-AD-2). The actor is NOT nullable -- nothing unattended writes
# here. The two JSON columns hold collector names, which are code and have no
# table to reference. `permissions` attaches `collectors.recollect_package`, the
# codename `core/roles.py` declares and `core/0013_grant_recollect` grants.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0014_evidence_time_indexes'),
        ('identity', '0004_version_authority_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRecollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('collectors', models.JSONField(blank=True, default=list, verbose_name='collectors')),
                ('not_offered', models.JSONField(blank=True, default=list, verbose_name='not offered')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_recollections', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recollections', to='identity.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'package recollection',
                'verbose_name_plural': 'package recollections',
                'db_table': 'package_recollections',
                'ordering': ('-observed_at', '-id'),
                'permissions': [('recollect_package', 'Can request a package recollection')],
                'indexes': [models.Index(fields=['package', '-observed_at'], name='recollection_pkg_observed')],
            },
        ),
    ]
