# Generated by Django 5.2.15 on 2026-09-14 07:11

# `operator_digests`: the daily operator digest, as composed from the run ledger,
# the inventory and the package table, and as delivered (CPM-OPERATE-S09).
# Otherwise unedited: the model declares the whole of it.
#
# An operator record on the human-audit tables' terms: append-only, one row a
# day, never purged (core/retention.py names it beside them), no relation to
# any other table and no unique constraint (CPM-AD-2). The two JSON columns hold
# the figures the next digest compares against and the outcome of each declared
# delivery -- `target` there is a webhook's host or an address, never a URL.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0015_package_recollections'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('window_start', models.DateTimeField(verbose_name='window start')),
                ('window_end', models.DateTimeField(verbose_name='window end')),
                ('figures', models.JSONField(blank=True, default=dict, verbose_name='figures')),
                ('text', models.TextField(verbose_name='text')),
                ('changed', models.BooleanField(verbose_name='changed')),
                ('deliveries', models.JSONField(blank=True, default=list, verbose_name='deliveries')),
                ('trace_id', models.CharField(blank=True, default='', max_length=32, verbose_name='trace id')),
            ],
            options={
                'verbose_name': 'operator digest',
                'verbose_name_plural': 'operator digests',
                'db_table': 'operator_digests',
                'ordering': ('-observed_at', '-id'),
                'indexes': [models.Index(fields=['-observed_at'], name='digest_observed')],
            },
        ),
    ]
