# Generated by Django 5.2.15 on 2026-09-14 02:16

# The four time-leading indexes on the two run ledgers (CPM-OPERATE-S07):
# `finished_at` and `started_at` on `collection_runs`, the purge's two cut-off
# scans; `finished_at` on `policy_runs`, its third; and `evidence_cutoff` on
# `policy_runs`, which the purge's floor rule range-probes once per candidate
# evidence row. Named per the `*_INDEX` constants in core/models.py. Otherwise
# unedited but for the dependency list, which names only this application's
# previous migration: an `AddIndex`-only migration touches no other table.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_grant_inventory_change'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectionrun',
            index=models.Index(fields=['finished_at'], name='collection_runs_finished'),
        ),
        migrations.AddIndex(
            model_name='collectionrun',
            index=models.Index(fields=['started_at'], name='collection_runs_started'),
        ),
        migrations.AddIndex(
            model_name='policyrun',
            index=models.Index(fields=['finished_at'], name='policy_runs_finished'),
        ),
        migrations.AddIndex(
            model_name='policyrun',
            index=models.Index(fields=['evidence_cutoff'], name='policy_runs_cutoff'),
        ),
    ]
