# Generated by Django 5.2.15 on 2026-09-14 10:03

# One index on the collection ledger for the package page's newest-runs read
# (CPM-OPERATE-S10): `(package, -started_at)`, so `recent_runs`' `ORDER BY
# started_at DESC, id DESC LIMIT 20` is twenty index entries rather than every
# run the package ever had, sorted. Demanded by a measured plan -- the story
# records the plan before and after -- and named per `COLLECTION_RUN_PACKAGE_INDEX`
# in core/models.py. Otherwise unedited: the models declare the whole of it,
# and the second dependency is what makemigrations wrote for the foreign key
# the index leads with.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_grant_recollect'),
        ('identity', '0004_version_authority_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectionrun',
            index=models.Index(fields=['package', '-started_at'], name='collection_runs_pkg_started'),
        ),
    ]
