# The two columns the rollup carries for inventory absence (CPM-OPERATE-S11):
# when the inventory was first seen not listing the package as of the run's
# cut-off, and when it last listed it. Both nullable and both `NULL` for a
# listed package; both written by the `collectors.mark_inventory_absence`
# after-run step rather than by the rollup writer, because `core` may not read
# the inventory's evidence table. Neither is a status: absence is an observation,
# not a verdict, and it gates nothing. Existing rows get `NULL`, which reads as
# "listed" until the next policy run stamps them -- honest, because no run has
# read absence at their cut-off yet.

# Generated by Django 5.2.15 on 2026-09-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_collection_run_package_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehealth',
            name='inventory_absent_since',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='inventory absent since'),
        ),
        migrations.AddField(
            model_name='packagehealth',
            name='inventory_last_listed',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='inventory last listed'),
        ),
    ]
